#!/bin/sh
# Copyright (C) 2006-2010 OpenWrt.org
# Copyright (C) 2010 Vertical Communications

rootfs_pivot() {
    check_skip || {
	echo "mounting rwroot"
	if [ -e /proc/cmdline ]; then
		spdev=$(awk 'BEGIN { RS=" "; FS="="; } $1 == "spdev" { print $2 }' < /proc/cmdline)
		if [ "$spdev" != "" ]; then
			mount -t squashfs -o relatime $spdev /sp_rom
			[ -e /sp_rom/fs/jffs2/jffs2.ko ] && insmod /sp_rom/fs/jffs2/jffs2.ko;
			mount | grep -q $spdev || mount -t jffs2 -o relatime $spdev /sp_rom
		fi
	fi
	
	mount -o move /tmp/overlay /overlay 2>&-
	fopivot /overlay /rom && pi_mount_skip_next=true
	echo "0" > /tmp/jffs2_ready
	}
}

boot_hook_add preinit_mount_root rootfs_pivot

