#!/bin/sh
# Copyright (C) 2006 OpenWrt.org
# Copyright (C) 2010 Vertical Communications

read_uc() {
	# directory /tmp/.uci will be used as a search path for config change files	
	mkdir -p /tmp/.uci
	chmod 0700 /tmp/.uci
	mkdir -p /var/state
	mkdir -p /var/lock
	
	# read user config data from UC zone
	uc_convert -t 0

	# if /tmp/uc/config exist, means that firmware was updated.
	if [ -e /tmp/uc/config ]; then
		# Merge factory usr config data with UC zone data, and clean garbage
		uc_convert -t 4
		# touch tmp file for other program
		touch /tmp/.update_firmware
	fi
}
      
boot_hook_add preinit_main read_uc
