#!/bin/sh /etc/rc.common
# Copyright (C) 2011 OpenWrt.org

START=98
RESUME=98

SERVICE_DAEMONIZE=1
SERVICE_WRITE_PID=1
SERVICE_PID_FILE=/var/run/sysntpd.pid

start() {
	local peers
	local args="-n"
	local enable_server
	local enable_ntp
	local usr_peer
	
	config_load system
	config_get usr_peer ntp server
	config_get peers ntp def_server
	config_get_bool enable_server ntp enable_server 0
	config_get enable_ntp basic timing_mode

	if [ "ntp" != "$enable_ntp" ]; then
		return
	fi

	if [ $enable_server -ne 0 ]; then
		append args "-l"
	fi
	
	if [ -n "$usr_peer" -a "$usr_peer" != "0.0.0.0" ]; then 
		append args "-p $usr_peer" 
	fi
	
	if [ -n "$peers" ]; then
		local peer
		for peer in $peers; do
			append args "-p $peer"
		done
	fi

	if [ "$args" != "-n" ]; then
		service_start /usr/sbin/ntpd $args
	fi
}

stop() {
	kill -9 `pgrep /usr/sbin/ntpd`
}

terminate() {
	stop
}

resume() {
	start
}
